CREATE TABLE IF NOT EXISTS `easymeal`.`:X_booking` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATE NULL,
  `number` INT NULL,
  `notes` VARCHAR(100) NULL,
  `status` VARCHAR(50) NULL,
  `creator` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_booking_creator_idx` (`creator` ASC),
  CONSTRAINT `fk_booking_creator_:X`
    FOREIGN KEY (`creator`)
    REFERENCES `easymeal`.`:prefixUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)