CREATE TABLE IF NOT EXISTS `easymeal`.`:X_Booking` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `client` INT NOT NULL,
    `date` DATETIME NOT NULL,
    `number` INT NOT NULL,
    `status` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX `fk_booking_client_idx` (`client` ASC),
    CONSTRAINT `fk_booking_client_:X`
    FOREIGN KEY (`client`)
    REFERENCES `easymeal`.`:prefixUser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)