CREATE TABLE IF NOT EXISTS `easymeal`.`:X_Menu_dish_association` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dish` INT NULL,
  `menu` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_dish_idx_idx:X`
    FOREIGN KEY (`dish`)
    REFERENCES `easymeal`.`:X_Dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_idx_idx:X`
    FOREIGN KEY (`menu`)
    REFERENCES `easymeal`.`:X_Menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  );
