version: '3'
services:
  web:
    build: site
    container_name: apache-pa
    ports :
     - "80:80"
    volumes:
     - ./www:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini

  database:
    image: mysql:5.7
    container_name: mysql
    ports :
      - "3306:3306"
    environment:
      MYSQL_DATABASE: easymeal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: easymeal
      MYSQL_PASSWORD: easymeal
    volumes:
      - ./db_data:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - database
    ports:
      - 8888:80
    environment:
        - PMA_ARBITRARY=1
