
/:
  controller: admin
  action: default

/manage:
  controller: admin
  action: default

/createarticle:
  controller: admin
  action: createArticle

/managepages:
  controller: admin
  action: managepages

/managearticles:
  controller: admin
  action: managearticles

/editarticle:
  controller: admin
  action: editarticle

