
/:
  controller: admin
  action: default

/manage:
  controller: admin
  action: default

/createarticle:
  controller: admin
  action: createArticle

/managearticles:
  controller: admin
  action: managearticles

/editarticle:
  controller: admin
  action: editarticle

/createpage:
  controller: admin
  action: createpage

/managepages:
  controller: admin
  action: managepages