
/:
  controller: admin
  action: default

/manage:
  controller: admin
  action: default

/article/create:
  controller: postcontroller
  action: createArticle

/articles:
  controller: postcontroller
  action: managearticles

/article/edit:
  controller: postcontroller
  action: editarticle

/article/delete:
  controller: postcontroller
  action: deletearticle

/page/create:
  controller: pagecontroller
  action: createpage

/pages:
  controller: pagecontroller
  action: managepages

/page/edit:
  controller: pagecontroller
  action: editpage

/deletepage:
  controller: pagecontroller
  action: deletepage

/searchdish:
  controller: dishController
  action: getDish

/dish/create:
  controller: dishController
  action: createdish

/dishes:
  controller: dishController
  action: managedishes

/dish/edit:
  controller: dishController
  action: editdish

/dish/delete:
  controller: dishController
  action: deletedish

/dishcategory/create:
  controller: dishCategoryController
  action: createdishCategory

/dishcategories:
  controller: dishCategoryController
  action: managedishcategories

/dishcategory/edit:
  controller: dishCategoryController
  action: editdishcategory

/dishcategory/delete:
  controller: dishCategoryController
  action: deletedishcategory

/comments:
  controller: commentController
  action: managecomments

/comment/delete:
  controller: commentController
  action: deletecomment

/menus:
  controller: menuController
  action: manageMenus
  
/menus/edit:
  controller: menuController
  action: editMenus

/menus/create:
  controller: menuController
  action: createMenu

/menus/delete:
  controller: menuController
  action: deleteMenu

/events:
  controller: eventController
  action: manageevents

/settings:
  controller: sitecontroller
  action: editsite

/medialibrary:
  controller: mediacontroller
  action: listMedias

/users:
  controller: usercontroller
  action: listadmin

/users/add:
  controller: usercontroller
  action: addadmin

/users/delete:
  controller: usercontroller
  action: deleteadmin

/ent/post:
  controller: postcontroller
  action: renderpost

/ent/dish:
  controller: dishController
  action: renderdish

/ent/menu:
  controller: menuController
  action: renderMenu
