
/:
  controller: admin
  action: default

/manage:
  controller: admin
  action: default

/createarticle:
  controller: postcontroller
  action: createArticle

/managearticles:
  controller: postcontroller
  action: managearticles

/editarticle:
  controller: postcontroller
  action: editarticle

/createpage:
  controller: pagecontroller
  action: createpage

/managepages:
  controller: pagecontroller
  action: managepages

/editpage:
  controller: pagecontroller
  action: editpage

/settings:
  controller: sitecontroller
  action: editsite

/ent/post:
  controller: postcontroller
  action: renderpost