
/:
  controller: admin
  action: default

/manage:
  controller: admin
  action: default

/createarticle:
  controller: postcontroller
  action: createArticle

/managearticles:
  controller: postcontroller
  action: managearticles

/editarticle:
  controller: postcontroller
  action: editarticle

/deletearticle:
  controller: postcontroller
  action: deletearticle

/createpage:
  controller: pagecontroller
  action: createpage

/managepages:
  controller: pagecontroller
  action: managepages

/editpage:
  controller: pagecontroller
  action: editpage

/deletepage:
  controller: pagecontroller
  action: deletepage

/searchdish:
  controller: dishController
  action: getDish

/createdish:
  controller: dishController
  action: createdish

/managedishes:
  controller: dishController
  action: managedishes

/editdish:
  controller: dishController
  action: editdish

/deletedish:
  controller: dishController
  action: deletedish

/createdishcategory:
  controller: dishCategoryController
  action: createdishCategory

/managedishcategories:
  controller: dishCategoryController
  action: managedishcategories

/editdishcategory:
  controller: dishCategoryController
  action: editdishcategory

/deletedishcategory:
  controller: dishCategoryController
  action: deletedishcategory

/managecomments:
  controller: commentController
  action: managecomments

/deletecomment:
  controller: commentController
  action: deletecomment

/menus:
  controller: menuController
  action: manageMenus
  
/menus/edit:
  controller: menuController
  action: editMenus

/menus/create:
  controller: menuController
  action: createMenu

/menus/delete:
  controller: menuController
  action: deleteMenu

/events:
  controller: eventController
  action: manageevents

/settings:
  controller: sitecontroller
  action: editsite

/medialibrary:
  controller: mediacontroller
  action: listMedias

/users:
  controller: usercontroller
  action: listadmin

/users/add:
  controller: usercontroller
  action: addadmin

/users/delete:
  controller: usercontroller
  action: deleteadmin

/ent/post:
  controller: postcontroller
  action: renderpost

/ent/dish:
  controller: dishController
  action: renderdish

/ent/menu:
  controller: menuController
  action: renderMenu
