
/:
  controller: admin
  action: default

/manage:
  controller: admin
  action: default

/createarticle:
  controller: admin
  action: createArticle

/test:
  controller: pageRenderer
  action: renderPage

