
/:
  controller: Main
  action: default

/admin:
  controller: Security
  action: default

/register:
  controller: Security
  action: register

/se-connecter:
  controller: Security
  action: login

/login:
  controller: Security
  action: login  

/se-deconnecter:
  controller: Security
  action: logout

/create:
  controller: ManageSite
  action: create


