
/:
  controller: Main
  action: default

/register:
  controller: Security
  action: register

/login:
  controller: Security
  action: login  

/logout:
  controller: Security
  action: logout

/create:
  controller: ManageSite
  action: create

/mailconfirm:
  controller: Security
  action: mailconfirm

/admin:
  controller: Admin
  action: default
  auth: true
  role: admin

/admin/sites:
  controller: Admin
  action: displaySites
  auth: true
  role: admin

/admin/site:
  controller: Admin
  action: displaySite
  auth: true
  role: admin

/admin/users:
  controller: Admin
  action: displayUsers
  auth: true
  role: admin

/admin/user:
  controller: Admin
  action: displayUser
  auth: true
  role: admin

/account/mysites:
  controller: Admin
  action: displayMySites
  auth: true
  role: admin
