
/:
  controller: Main
  action: default

/register:
  controller: Security
  action: register
  middleware: noAuth

/login:
  controller: Security
  action: login  
  middleware: noAuth

/logout:
  controller: Security
  action: logout
  middleware: auth

/create:
  controller: ManageSite
  action: create
  middleware: auth

/mailconfirm:
  controller: Security
  action: mailconfirm

# authenticated user routes
/account:
  controller: Account
  action: default
  middleware: auth
  
/account/mysites:
  controller: Account
  action: mysites
  middleware: auth

/api/users:
  controller: Account
  action: searchUsers
  middleware: auth

# admin routes
/admin:
  controller: Admin
  action: default

/admin/sites:
  controller: Admin
  action: displaySites

/admin/site:
  controller: Admin
  action: displaySite

/admin/users:
  controller: Admin
  action: displayUsers

/admin/user:
  controller: Admin
  action: displayUser

/admin/roles:
  controller: Admin
  action: displayRoles

/admin/role:
  controller: Admin
  action: editrole

