
/:
  controller: Main
  action: default

/register:
  controller: Security
  action: register
  middleware: noAuth

/login:
  controller: Security
  action: login  
  middleware: noAuth

/logout:
  controller: Security
  action: logout
  middleware: auth

/create:
  controller: ManageSite
  action: create
  middleware: auth

/mailconfirm:
  controller: Security
  action: mailconfirm

# authenticated user routes
/account:
  controller: Account
  action: default
  middleware: auth
  
/account/password:
  controller: Account
  action: updatePassword
  middleware: auth

/account/sites:
  controller: Account
  action: mysites
  middleware: auth

/api/users:
  controller: Account
  action: searchUsers
  middleware: auth

# admin routes
/admin:
  controller: Admin
  action: default
  middleware: isAdmin

/admin/sites:
  controller: Admin
  action: displaySites
  middleware: isAdmin

/admin/site:
  controller: Admin
  action: displaySite
  middleware: isAdmin

/admin/users:
  controller: Admin
  action: displayUsers
  middleware: isAdmin

/admin/user:
  controller: Admin
  action: displayUser
  middleware: isAdmin

/admin/roles:
  controller: Admin
  action: displayRoles
  middleware: isAdmin

/admin/role:
  controller: Admin
  action: editrole
  middleware: isAdmin

