
/:
  controller: Main
  action: default

/admin:
  controller: Security
  action: default
  auth: true
  role: admin

/register:
  controller: Security
  action: register

/login:
  controller: Security
  action: login  

/logout:
  controller: Security
  action: logout

/create:
  controller: ManageSite
  action: create


